apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-12T14:23:01Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5470"
  uid: 3dce9b8f-9835-45f5-a133-25f9d6be1c7d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.156.159
  clusterIPs:
  - 10.101.156.159
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31383
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
